import { getChecklistAdminData } from "@/src/application/checklists/admin";
import { requirePermission } from "@/src/infrastructure/auth/permissions";
import { createChecklistTask, toggleChecklistTask } from "./actions";
export const dynamic = "force-dynamic";
export default async function AdminChecklistsPage() {
  const { organizationId } = await requirePermission("checklist.manage");
  const data = await getChecklistAdminData(organizationId, process.env.DEFAULT_STORE_CODE ?? "TEPEXI");
  return <main className="shell"><section className="hero"><p className="eyebrow">ADMIN · CHECKLISTS</p><h1>Tareas operativas</h1><p className="muted">Crear/desactivar tareas modifica futuras corridas; las corridas históricas conservan su snapshot.</p></section>
  <section className="grid"><article className="card"><h2>Nueva tarea</h2><form action={createChecklistTask} className="stack"><label>Checklist<select name="templateId" required>{data.templates.map(t=><option value={t.id} key={t.id}>{t.name} · {t.shiftType}</option>)}</select></label><label>Tarea<input name="title" required/></label><label>Área<input name="area" defaultValue="Operación"/></label><label>Prioridad<select name="priority" defaultValue="NORMAL"><option>OPENING_CRITICAL</option><option>NORMAL</option></select></label><label>Entrada<select name="inputType" defaultValue="BOOLEAN"><option>BOOLEAN</option><option>NUMBER</option><option>TEXT</option><option>TEMPERATURE</option><option>WEIGHT</option><option>TIME</option></select></label><label>RRULE<input name="rrule" placeholder="FREQ=WEEKLY;BYDAY=FR"/></label><label>SOP<select name="sopId"><option value="">Sin SOP</option>{data.sopOptions.map(s=><option value={s.id} key={s.id}>{s.title}</option>)}</select></label><label>Orden<input name="sortOrder" type="number" defaultValue="1000"/></label><label><input name="required" type="checkbox" defaultChecked style={{width:'auto'}}/> Obligatoria</label><button type="submit">Crear tarea</button></form></article>
  <article className="card"><h2>Tareas actuales</h2>{data.tasks.map(t=><div className="task" key={t.id}><div style={{flex:1}}><strong>{t.title}</strong><div className="muted">{t.area} · {t.inputType} · {t.rrule ?? 'Siempre'}</div></div><form action={toggleChecklistTask}><input type="hidden" name="taskId" value={t.id}/><input type="hidden" name="active" value={String(!t.active)}/><button type="submit">{t.active?'Desactivar':'Activar'}</button></form></div>)}</article></section></main>;
}
